# Generated by Django 4.0.6 on 2022-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_designation_mst_employee_mst_delete_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_mst',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
